# boot and facade
xpcore_facade_module_name: "xposer.sample_app.rpc_kafka.sample_app_kafka_facade"
xpcore_facade_class_name: "SampleAppKafkaFacade"
xpcore_highlevel_variable: "passed"
xpcore_log_to_console_enabled: "true"
xpcore_log_to_console_loglevel: "DEBUG"
xpcore_log_to_kafka_enabled: "true"
xpcore_log_to_kafka_server_string: "0.0.0.0:9092"

# Built-in config
xpfacade_kafka_inbound_topic: "router_inbound"
xpfacade_kafka_outbound_topic: "router_outbound"
xpfacade_kafka_exception_topic: "router_exception"
xpfacade_kafka_server_string: "0.0.0.0:9092"
xpfacade_kafka_group_id: "router"
xpfacade_kafka_bar: "baz"

# App Sub config
xpapp_kafka_logic_param_to_override: "not_jens"